FROM debian

MAINTAINER bsharna <bsharna@student.21-school.ru>

RUN apt-get update -y && apt-get upgrade -y && apt-get install vim -y

ENTRYPOINT vim

# docker build -t ex00 .

# docker run --rm -it ex00
